import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
	title: "next-auth-15o1",
	description: "Generated by hanifaahmadov.site",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={``}>
				<div
					className='root-layout h-[100svh] w-[100svw] 
                        flex flex-col justify-center items-center 
						fixed inset-0
                        bg-zinc-950 text-neutral-100'
				>
					{children}
				</div>
			</body>
		</html>
	);
}
